### ISSUE TITLE
Got errors when running demo.sh

### ISSUE THREAD

**Issue by dragove** [sanghyun-son/EDSR-PyTorch#50]
I follow the steps from the readme file to run the demo file with Windows 10 x64 + python 3.6.6 + pytorch 0.4.1 cuda92.
Firstly I got a division by zero exception. And I place DIV2K to the database folder. It cause another error. It prints error messages here:

PS D:\Document\Python\EDSR-PyTorch\code> sh demo.sh
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]       Learning rate: 1.00e-4
rm: cannot remove '../experiment/RCAN_BIX2_G10R20P48/log.txt': Device or resource busy
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]       Learning rate: 1.00e-4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "D:\Document\Python\EDSR-PyTorch\code\trainer.py", line 45, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "D:\Document\Python\EDSR-PyTorch\code\dataloader.py", line 144, in __iter__
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    return _MSDataLoaderIter(self)
  File "D:\Document\Python\EDSR-PyTorch\code\dataloader.py", line 117, in __init__
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    self._popen = self._Popen(self)
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    return _default_context.get_context().Process._Popen(process_obj)
run_name="__mp_main__")  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    return Popen(process_obj)
      File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
reduction.dump(process_obj, to_child)
exec(code, run_globals)  File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump

  File "D:\Document\Python\EDSR-PyTorch\code\main.py", line 19, in <module>
    ForkingPickler(file, protocol).dump(obj)
    BrokenPipeErrort.train():
[Errno 32] Broken pipe  File "D:\Document\Python\EDSR-PyTorch\code\trainer.py", line 45, in train

    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "D:\Document\Python\EDSR-PyTorch\code\dataloader.py", line 144, in __iter__
    return _MSDataLoaderIter(self)
  File "D:\Document\Python\EDSR-PyTorch\code\dataloader.py", line 117, in __init__
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

I do not know the code, so I can not modify by myself. I would be thankful if you could give me some advice. Thanks.

**Comment by drStacky** [comment]
Not sure about your second problem, but I've gotten many division by zero exceptions when it couldn't find my images.

**Comment by thstkdgus35** [comment]
Hello.

Unfortunately, we do not officially support Windows since our lab does not have any Windows-GPU machine.

One possible solution can be setting ``--n_threads 0 or 1``.

If it does not work, I will find the way for the Windows as much as I can.

Thank you.

**Comment by TheDeadCode** [comment]
When appending `--n_threads 0`, this error pops:

```
Evaluation:
  0%|                                                     | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 18, in <module>
    while not t.terminate():
  File "C:\1-Dev\Testing\EDSR-PyTorch\code\trainer.py", line 138, in terminate
    self.test()
  File "C:\1-Dev\Testing\EDSR-PyTorch\code\trainer.py", line 88, in test
    for idx_img, (lr, hr, filename, _) in enumerate(tqdm_test):
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by JoeBlack27** [comment]
meet that same problem as with @TheDeadCode , but do not know how to solve it.

**Comment by kice** [comment]
Change `multiprocessing` to `threading`, and change all `multiprocessing.Queue` to `queue.Queue`.

Since `multiprocessing` is different in Linux and Windows, it should work after change them into `threading`.

```
import sys
import threading
import queue
import random
import collections

import torch
import torch.multiprocessing as multiprocessing

from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
    _remove_worker_pids, _error_if_any_worker_fails
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.dataloader import _DataLoaderIter

from torch.utils.data.dataloader import ExceptionWrapper
from torch.utils.data.dataloader import _use_shared_memory
from torch.utils.data.dataloader import _worker_manager_loop
from torch.utils.data.dataloader import numpy_type_map
from torch.utils.data.dataloader import default_collate
from torch.utils.data.dataloader import pin_memory_batch
from torch.utils.data.dataloader import _SIGCHLD_handler_set
from torch.utils.data.dataloader import _set_SIGCHLD_handler

if sys.version_info[0] == 2:
    import Queue as queue
else:
    import queue

def _ms_loop(dataset, index_queue, data_queue, collate_fn, scale, seed, init_fn, worker_id):
    global _use_shared_memory
    _use_shared_memory = True
    _set_worker_signal_handlers()

    torch.set_num_threads(1)
    torch.manual_seed(seed)
    while True:
        r = index_queue.get()
        if r is None:
            break
        idx, batch_indices = r
        try:
            idx_scale = 0
            if len(scale) > 1 and dataset.train:
                idx_scale = random.randrange(0, len(scale))
                dataset.set_scale(idx_scale)

            samples = collate_fn([dataset[i] for i in batch_indices])
            samples.append(idx_scale)

        except Exception:
            data_queue.put((idx, ExceptionWrapper(sys.exc_info())))
        else:
            data_queue.put((idx, samples))

class _MSDataLoaderIter(_DataLoaderIter):
    def __init__(self, loader):
        self.dataset = loader.dataset
        self.scale = loader.scale
        self.collate_fn = loader.collate_fn
        self.batch_sampler = loader.batch_sampler
        self.num_workers = loader.num_workers
        self.pin_memory = loader.pin_memory and torch.cuda.is_available()
        self.timeout = loader.timeout
        self.done_event = threading.Event()

        self.sample_iter = iter(self.batch_sampler)

        if self.num_workers > 0:
            self.worker_init_fn = loader.worker_init_fn
            self.index_queues = [
                queue.Queue() for _ in range(self.num_workers)
            ]
            self.worker_queue_idx = 0
            self.worker_result_queue = queue.Queue()
            self.batches_outstanding = 0
            self.worker_pids_set = False
            self.shutdown = False
            self.send_idx = 0
            self.rcvd_idx = 0
            self.reorder_dict = {}

            base_seed = torch.LongTensor(1).random_()[0]
            self.workers = [
                threading.Thread(
                    target=_ms_loop,
                    args=(
                        self.dataset,
                        self.index_queues[i],
                        self.worker_result_queue,
                        self.collate_fn,
                        self.scale,
                        base_seed + i,
                        self.worker_init_fn,
                        i
                    )
                )
                for i in range(self.num_workers)]

            if self.pin_memory or self.timeout > 0:
                self.data_queue = queue.Queue()
                if self.pin_memory:
                    maybe_device_id = torch.cuda.current_device()
                else:
                    # do not initialize cuda context if not necessary
                    maybe_device_id = None
                self.worker_manager_thread = threading.Thread(
                    target=_worker_manager_loop,
                    args=(self.worker_result_queue, self.data_queue, self.done_event, self.pin_memory,
                          maybe_device_id))
                self.worker_manager_thread.daemon = True
                self.worker_manager_thread.start()
            else:
                self.data_queue = self.worker_result_queue

            for w in self.workers:
                w.daemon = True  # ensure that the worker exits on process exit
                w.start()

            #_update_worker_pids(id(self), tuple(w.pid for w in self.workers))
            #_set_SIGCHLD_handler()
            #self.worker_pids_set = True

            # prime the prefetch loop
            for _ in range(2 * self.num_workers):
                self._put_indices()

class MSDataLoader(DataLoader):
    def __init__(
        self, args, dataset, batch_size=1, shuffle=False,
        sampler=None, batch_sampler=None,
        collate_fn=default_collate, pin_memory=False, drop_last=False,
        timeout=0, worker_init_fn=None):

        super(MSDataLoader, self).__init__(
            dataset, batch_size=batch_size, shuffle=shuffle,
            sampler=sampler, batch_sampler=batch_sampler,
            num_workers=args.n_threads, collate_fn=collate_fn,
            pin_memory=pin_memory, drop_last=drop_last,
            timeout=timeout, worker_init_fn=worker_init_fn)

        self.scale = args.scale

    def __iter__(self):
        return _MSDataLoaderIter(self)
```

**Comment by Masood-Lapeh** [comment]
I've got division by zero exception too. Do I really need to download DIV2K dataset in order to just run the pre-trained models?

**Comment by thstkdgus35** [comment]
You do not have to download DIV2K images to execute pre-trained models.

Just put your test image in a ``test`` folder and run [this script](https://github.com/thstkdgus35/EDSR-PyTorch/blob/70294bb6170651dd1c2435da18a34c0e2cf63511/src/demo.sh#L32).

Also, replace [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/70294bb6170651dd1c2435da18a34c0e2cf63511/src/data/srdata.py#L80) by ``self.repeat = 1`` to avoid the error message.

I will fix the error soon.

Thank you!

**Comment by Masood-Lapeh** [comment]
Thank you.

About this error:

```
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

I've changed `main.py` like this:

```
def run():
    global model
    global checkpoint
    
    torch.multiprocessing.freeze_support()
    
    torch.manual_seed(args.seed)
    checkpoint = utility.checkpoint(args)

    if args.data_test == 'video':
        model = model.Model(args, checkpoint)
        t = VideoTester(args, model, checkpoint)
        t.test()
    else:
        if checkpoint.ok:
            loader = data.Data(args)
            model = model.Model(args, checkpoint)
            loss = loss.Loss(args, checkpoint) if not args.test_only else None
            t = Trainer(args, loader, model, loss, checkpoint)
            while not t.terminate():
                t.train()
                t.test()

            checkpoint.done()

if __name__ == '__main__':
    run()
```

And It's gone. But another error still remains:

```

Evaluation:
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    run()
  File "main.py", line 30, in run
    while not t.terminate():
  File "C:\Users\Masood\Documents\Dev\zooom\EDSR-PyTorch-new\src\trainer.py", line 141, in terminate
    self.test()
  File "C:\Users\Masood\Documents\Dev\zooom\EDSR-PyTorch-new\src\trainer.py", line 87, in test
    if self.args.save_results: self.ckp.begin_background()
  File "C:\Users\Masood\Documents\Dev\zooom\EDSR-PyTorch-new\src\utility.py", line 145, in begin_background
    for p in self.process: p.start()
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'
```

And also another exception arises after that:

```
(env) C:\Users\Masood\Documents\Dev\zooom\EDSR-PyTorch-new\src>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\users\masood\appdata\local\programs\python\python36\Lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

Not that I'm using this line:
```
python main.py --data_test Demo --scale 4 --pre_train download --test_only --save_results --n_threads 0
```

**Comment by mwk0423** [comment]
hello,
Have your problem solved
I have same error  

> AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'

and

> EOFError: Ran out of input

 the script i execute
`python main.py --data_test Demo --scale 4 --pre_train ../experiment/EDSR_x2/model/model_best.pt --test_only --save_results`

I'v appreciate for advise.

**Comment by mwk0423** [comment]
hi,
You can try replace the utility.py file to:
`import os
import math
import time
import datetime
from multiprocessing import Process
from multiprocessing import Queue

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import numpy as np
import imageio

import torch
import torch.optim as optim
import torch.optim.lr_scheduler as lrs

class timer():
    def __init__(self):
        self.acc = 0
        self.tic()

    def tic(self):
        self.t0 = time.time()

    def toc(self, restart=False):
        diff = time.time() - self.t0
        if restart: self.t0 = time.time()
        return diff

    def hold(self):
        self.acc += self.toc()

    def release(self):
        ret = self.acc
        self.acc = 0

        return ret

    def reset(self):
        self.acc = 0

#redefine bg_target
def bg_target(queue):
    while True:
        if not queue.empty():
            filename, tensor = queue.get()
            if filename is None: break
            imageio.imwrite(filename, tensor.numpy())
            
class checkpoint():
    def __init__(self, args):
        self.args = args
        self.ok = True
        self.log = torch.Tensor()
        now = datetime.datetime.now().strftime('%Y-%m-%d-%H:%M:%S')

        if not args.load:
            if not args.save:
                args.save = now
            self.dir = os.path.join('..', 'experiment', args.save)
        else:
            self.dir = os.path.join('..', 'experiment', args.load)
            if os.path.exists(self.dir):
                self.log = torch.load(self.get_path('psnr_log.pt'))
                print('Continue from epoch {}...'.format(len(self.log)))
            else:
                args.load = ''

        if args.reset:
            os.system('rm -rf ' + self.dir)
            args.load = ''

        os.makedirs(self.dir, exist_ok=True)
        os.makedirs(self.get_path('model'), exist_ok=True)
        for d in args.data_test:
            os.makedirs(self.get_path('results-{}'.format(d)), exist_ok=True)

        open_type = 'a' if os.path.exists(self.get_path('log.txt'))else 'w'
        self.log_file = open(self.get_path('log.txt'), open_type)
        with open(self.get_path('config.txt'), open_type) as f:
            f.write(now + '\n\n')
            for arg in vars(args):
                f.write('{}: {}\n'.format(arg, getattr(args, arg)))
            f.write('\n')

        self.n_processes = 8

    def get_path(self, *subdir):
        return os.path.join(self.dir, *subdir)

    def save(self, trainer, epoch, is_best=False):
        trainer.model.save(self.get_path('model'), epoch, is_best=is_best)
        trainer.loss.save(self.dir)
        trainer.loss.plot_loss(self.dir, epoch)

        self.plot_psnr(epoch)
        trainer.optimizer.save(self.dir)
        torch.save(self.log, self.get_path('psnr_log.pt'))

    def add_log(self, log):
        self.log = torch.cat([self.log, log])

    def write_log(self, log, refresh=False):
        print(log)
        self.log_file.write(log + '\n')
        if refresh:
            self.log_file.close()
            self.log_file = open(self.get_path('log.txt'), 'a')

    def done(self):
        self.log_file.close()

    def plot_psnr(self, epoch):
        axis = np.linspace(1, epoch, epoch)
        for idx_data, d in enumerate(self.args.data_test):
            label = 'SR on {}'.format(d)
            fig = plt.figure()
            plt.title(label)
            for idx_scale, scale in enumerate(self.args.scale):
                plt.plot(
                    axis,
                    self.log[:, idx_data, idx_scale].numpy(),
                    label='Scale {}'.format(scale)
                )
            plt.legend()
            plt.xlabel('Epochs')
            plt.ylabel('PSNR')
            plt.grid(True)
            plt.savefig(self.get_path('test_{}.pdf'.format(d)))
            plt.close(fig)
    '''    def begin_background(self):
        self.queue = Queue()

        def bg_target(queue):
            while True:
                if not queue.empty():
                    filename, tensor = queue.get()
                    if filename is None: break
                    imageio.imwrite(filename, tensor.numpy())
        
        self.process = [
            Process(target=bg_target, args=(self.queue,)) \
            for _ in range(self.n_processes)
        ]
        
        for p in self.process: p.start()'''

    def begin_background(self):
        self.queue = Queue()

        self.process = [
            Process(target=bg_target, args=(self.queue,)) \
            for _ in range(self.n_processes)
        ]

        for p in self.process: p.start()

    def end_background(self):
        for _ in range(self.n_processes): self.queue.put((None, None))
        while not self.queue.empty(): time.sleep(1)
        for p in self.process: p.join()

    def save_results(self, dataset, filename, save_list, scale):
        if self.args.save_results:
            filename = self.get_path(
                'results-{}'.format(dataset.dataset.name),
                '{}_x{}_'.format(filename, scale)
            )

            postfix = ('SR', 'LR', 'HR')
            for v, p in zip(save_list, postfix):
                normalized = v[0].mul(255 / self.args.rgb_range)
                tensor_cpu = normalized.byte().permute(1, 2, 0).cpu()
                self.queue.put(('{}{}.png'.format(filename, p), tensor_cpu))

def quantize(img, rgb_range):
    pixel_range = 255 / rgb_range
    return img.mul(pixel_range).clamp(0, 255).round().div(pixel_range)

def calc_psnr(sr, hr, scale, rgb_range, dataset=None):
    if hr.nelement() == 1: return 0

    diff = (sr - hr) / rgb_range
    if dataset and dataset.dataset.benchmark:
        shave = scale
        if diff.size(1) > 1:
            gray_coeffs = [65.738, 129.057, 25.064]
            convert = diff.new_tensor(gray_coeffs).view(1, 3, 1, 1) / 256
            diff = diff.mul(convert).sum(dim=1)
    else:
        shave = scale + 6

    valid = diff[..., shave:-shave, shave:-shave]
    mse = valid.pow(2).mean()

    return -10 * math.log10(mse)

# redefine lambda x: x.requires_grad
def return_x(x):
    return x.requires_grad

#redefine lambda x: int(x)
def return_y(y):
    return int(y)

def make_optimizer(args, target):
    '''
        make optimizer and scheduler together
    '''
    # optimizer
    trainable = filter(return_x, target.parameters())
    kwargs_optimizer = {'lr': args.lr, 'weight_decay': args.weight_decay}

    if args.optimizer == 'SGD':
        optimizer_class = optim.SGD
        kwargs_optimizer['momentum'] = args.momentum
    elif args.optimizer == 'ADAM':
        optimizer_class = optim.Adam
        kwargs_optimizer['betas'] = args.betas
        kwargs_optimizer['eps'] = args.epsilon
    elif args.optimizer == 'RMSprop':
        optimizer_class = optim.RMSprop
        kwargs_optimizer['eps'] = args.epsilon

    # scheduler
    milestones = list(map(return_y, args.decay.split('-')))
    kwargs_scheduler = {'milestones': milestones, 'gamma': args.gamma}
    scheduler_class = lrs.MultiStepLR

    class CustomOptimizer(optimizer_class):
        def __init__(self, *args, **kwargs):
            super(CustomOptimizer, self).__init__(*args, **kwargs)

        def _register_scheduler(self, scheduler_class, **kwargs):
            self.scheduler = scheduler_class(self, **kwargs)

        def save(self, save_dir):
            torch.save(self.state_dict(), self.get_dir(save_dir))

        def load(self, load_dir, epoch=1):
            self.load_state_dict(torch.load(self.get_dir(load_dir)))
            if epoch > 1:
                for _ in range(epoch): self.scheduler.step()

        def get_dir(self, dir_path):
            return os.path.join(dir_path, 'optimizer.pt')

        def schedule(self):
            self.scheduler.step()

        def get_lr(self):
            return self.scheduler.get_lr()[0]

        def get_last_epoch(self):
            return self.scheduler.last_epoch
    
    optimizer = CustomOptimizer(trainable, **kwargs_optimizer)
    optimizer._register_scheduler(scheduler_class, **kwargs_scheduler)
    return optimizer

` 

I'm not familiar with python，however i can execute it after change my utility.py.

**Comment by tabetomo** [comment]
It seems that the second issue is the same as #88 and #91.

**Comment by Losstie** [comment]
Hi,when I try to test this model only by quick start(demo) and I also comment proper line,but  the following error occurred!

Making model...
Download the model

Evaluation:
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 26, in main
    while not t.terminate():
  File "D:\Project\Competition\SR_YOUKU\EDSR-PyTorch\src\trainer.py", line 139, in terminate
    self.test()
  File "D:\Project\Competition\SR_YOUKU\EDSR-PyTorch\src\trainer.py", line 83, in test
    if self.args.save_results: self.ckp.begin_background()
  File "D:\Project\Competition\SR_YOUKU\EDSR-PyTorch\src\utility.py", line 141, in begin_background
    for p in self.process: p.start()
  File "G:\DevelopEnvironment\Anaconda3\envs\my_torch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "G:\DevelopEnvironment\Anaconda3\envs\my_torch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "G:\DevelopEnvironment\Anaconda3\envs\my_torch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "G:\DevelopEnvironment\Anaconda3\envs\my_torch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "G:\DevelopEnvironment\Anaconda3\envs\my_torch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'
(my_torch)
losstie@LAPTOP-JNJDDSKD MINGW64 /d/Project/Competition/SR_YOUKU/EDSR-PyTorch/src (master)
$ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\DevelopEnvironment\Anaconda3\envs\my_torch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "G:\DevelopEnvironment\Anaconda3\envs\my_torch\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by TigerStone93** [comment]
I've tried almost every solution that issues in this repository suggested, however it doesn't make any change. In my opinion, this code is too vulnerable to run in various environments of all users. Maybe I should find another implementation of EDSR.

**Comment by T5eng** [comment]
> hi,
> You can try replace the utility.py file to:
> 
> ```
> `import os
> import math
> import time
> import datetime
> from multiprocessing import Process
> from multiprocessing import Queue
> 
> import matplotlib
> matplotlib.use('Agg')
> import matplotlib.pyplot as plt
> 
> import numpy as np
> import imageio
> 
> import torch
> import torch.optim as optim
> import torch.optim.lr_scheduler as lrs
> 
> class timer():
>     def __init__(self):
>         self.acc = 0
>         self.tic()
> 
>     def tic(self):
>         self.t0 = time.time()
> 
>     def toc(self, restart=False):
>         diff = time.time() - self.t0
>         if restart: self.t0 = time.time()
>         return diff
> 
>     def hold(self):
>         self.acc += self.toc()
> 
>     def release(self):
>         ret = self.acc
>         self.acc = 0
> 
>         return ret
> 
>     def reset(self):
>         self.acc = 0
> 
> #redefine bg_target
> def bg_target(queue):
>     while True:
>         if not queue.empty():
>             filename, tensor = queue.get()
>             if filename is None: break
>             imageio.imwrite(filename, tensor.numpy())
>             
> class checkpoint():
>     def __init__(self, args):
>         self.args = args
>         self.ok = True
>         self.log = torch.Tensor()
>         now = datetime.datetime.now().strftime('%Y-%m-%d-%H:%M:%S')
> 
>         if not args.load:
>             if not args.save:
>                 args.save = now
>             self.dir = os.path.join('..', 'experiment', args.save)
>         else:
>             self.dir = os.path.join('..', 'experiment', args.load)
>             if os.path.exists(self.dir):
>                 self.log = torch.load(self.get_path('psnr_log.pt'))
>                 print('Continue from epoch {}...'.format(len(self.log)))
>             else:
>                 args.load = ''
> 
>         if args.reset:
>             os.system('rm -rf ' + self.dir)
>             args.load = ''
> 
>         os.makedirs(self.dir, exist_ok=True)
>         os.makedirs(self.get_path('model'), exist_ok=True)
>         for d in args.data_test:
>             os.makedirs(self.get_path('results-{}'.format(d)), exist_ok=True)
> 
>         open_type = 'a' if os.path.exists(self.get_path('log.txt'))else 'w'
>         self.log_file = open(self.get_path('log.txt'), open_type)
>         with open(self.get_path('config.txt'), open_type) as f:
>             f.write(now + '\n\n')
>             for arg in vars(args):
>                 f.write('{}: {}\n'.format(arg, getattr(args, arg)))
>             f.write('\n')
> 
>         self.n_processes = 8
> 
>     def get_path(self, *subdir):
>         return os.path.join(self.dir, *subdir)
> 
>     def save(self, trainer, epoch, is_best=False):
>         trainer.model.save(self.get_path('model'), epoch, is_best=is_best)
>         trainer.loss.save(self.dir)
>         trainer.loss.plot_loss(self.dir, epoch)
> 
>         self.plot_psnr(epoch)
>         trainer.optimizer.save(self.dir)
>         torch.save(self.log, self.get_path('psnr_log.pt'))
> 
>     def add_log(self, log):
>         self.log = torch.cat([self.log, log])
> 
>     def write_log(self, log, refresh=False):
>         print(log)
>         self.log_file.write(log + '\n')
>         if refresh:
>             self.log_file.close()
>             self.log_file = open(self.get_path('log.txt'), 'a')
> 
>     def done(self):
>         self.log_file.close()
> 
>     def plot_psnr(self, epoch):
>         axis = np.linspace(1, epoch, epoch)
>         for idx_data, d in enumerate(self.args.data_test):
>             label = 'SR on {}'.format(d)
>             fig = plt.figure()
>             plt.title(label)
>             for idx_scale, scale in enumerate(self.args.scale):
>                 plt.plot(
>                     axis,
>                     self.log[:, idx_data, idx_scale].numpy(),
>                     label='Scale {}'.format(scale)
>                 )
>             plt.legend()
>             plt.xlabel('Epochs')
>             plt.ylabel('PSNR')
>             plt.grid(True)
>             plt.savefig(self.get_path('test_{}.pdf'.format(d)))
>             plt.close(fig)
>     '''    def begin_background(self):
>         self.queue = Queue()
> 
>         def bg_target(queue):
>             while True:
>                 if not queue.empty():
>                     filename, tensor = queue.get()
>                     if filename is None: break
>                     imageio.imwrite(filename, tensor.numpy())
>         
>         self.process = [
>             Process(target=bg_target, args=(self.queue,)) \
>             for _ in range(self.n_processes)
>         ]
>         
>         for p in self.process: p.start()'''
> 
>     def begin_background(self):
>         self.queue = Queue()
> 
>         self.process = [
>             Process(target=bg_target, args=(self.queue,)) \
>             for _ in range(self.n_processes)
>         ]
> 
>         for p in self.process: p.start()
> 
>     def end_background(self):
>         for _ in range(self.n_processes): self.queue.put((None, None))
>         while not self.queue.empty(): time.sleep(1)
>         for p in self.process: p.join()
> 
>     def save_results(self, dataset, filename, save_list, scale):
>         if self.args.save_results:
>             filename = self.get_path(
>                 'results-{}'.format(dataset.dataset.name),
>                 '{}_x{}_'.format(filename, scale)
>             )
> 
>             postfix = ('SR', 'LR', 'HR')
>             for v, p in zip(save_list, postfix):
>                 normalized = v[0].mul(255 / self.args.rgb_range)
>                 tensor_cpu = normalized.byte().permute(1, 2, 0).cpu()
>                 self.queue.put(('{}{}.png'.format(filename, p), tensor_cpu))
> 
> def quantize(img, rgb_range):
>     pixel_range = 255 / rgb_range
>     return img.mul(pixel_range).clamp(0, 255).round().div(pixel_range)
> 
> def calc_psnr(sr, hr, scale, rgb_range, dataset=None):
>     if hr.nelement() == 1: return 0
> 
>     diff = (sr - hr) / rgb_range
>     if dataset and dataset.dataset.benchmark:
>         shave = scale
>         if diff.size(1) > 1:
>             gray_coeffs = [65.738, 129.057, 25.064]
>             convert = diff.new_tensor(gray_coeffs).view(1, 3, 1, 1) / 256
>             diff = diff.mul(convert).sum(dim=1)
>     else:
>         shave = scale + 6
> 
>     valid = diff[..., shave:-shave, shave:-shave]
>     mse = valid.pow(2).mean()
> 
>     return -10 * math.log10(mse)
> 
> # redefine lambda x: x.requires_grad
> def return_x(x):
>     return x.requires_grad
> 
> #redefine lambda x: int(x)
> def return_y(y):
>     return int(y)
> 
> def make_optimizer(args, target):
>     '''
>         make optimizer and scheduler together
>     '''
>     # optimizer
>     trainable = filter(return_x, target.parameters())
>     kwargs_optimizer = {'lr': args.lr, 'weight_decay': args.weight_decay}
> 
>     if args.optimizer == 'SGD':
>         optimizer_class = optim.SGD
>         kwargs_optimizer['momentum'] = args.momentum
>     elif args.optimizer == 'ADAM':
>         optimizer_class = optim.Adam
>         kwargs_optimizer['betas'] = args.betas
>         kwargs_optimizer['eps'] = args.epsilon
>     elif args.optimizer == 'RMSprop':
>         optimizer_class = optim.RMSprop
>         kwargs_optimizer['eps'] = args.epsilon
> 
>     # scheduler
>     milestones = list(map(return_y, args.decay.split('-')))
>     kwargs_scheduler = {'milestones': milestones, 'gamma': args.gamma}
>     scheduler_class = lrs.MultiStepLR
> 
>     class CustomOptimizer(optimizer_class):
>         def __init__(self, *args, **kwargs):
>             super(CustomOptimizer, self).__init__(*args, **kwargs)
> 
>         def _register_scheduler(self, scheduler_class, **kwargs):
>             self.scheduler = scheduler_class(self, **kwargs)
> 
>         def save(self, save_dir):
>             torch.save(self.state_dict(), self.get_dir(save_dir))
> 
>         def load(self, load_dir, epoch=1):
>             self.load_state_dict(torch.load(self.get_dir(load_dir)))
>             if epoch > 1:
>                 for _ in range(epoch): self.scheduler.step()
> 
>         def get_dir(self, dir_path):
>             return os.path.join(dir_path, 'optimizer.pt')
> 
>         def schedule(self):
>             self.scheduler.step()
> 
>         def get_lr(self):
>             return self.scheduler.get_lr()[0]
> 
>         def get_last_epoch(self):
>             return self.scheduler.last_epoch
>     
>     optimizer = CustomOptimizer(trainable, **kwargs_optimizer)
>     optimizer._register_scheduler(scheduler_class, **kwargs_scheduler)
>     return optimizer
> 
> ` 
> ```
> 
> I'm not familiar with python，however i can execute it after change my utility.py.

Awesome, dude! I ve been struggling for hours. you saved my life. LOL

**Comment by praful1993** [comment]
Thank you so much @T5eng.
You saved my  time..........
